//! LLM Engine — Safe Rust wrapper around llama.cpp FFI.
//!
//! Provides `LlamaEngine` for model loading, tokenization, encoding, and generation,
//! plus `mask_builder` for per-head topological attention masking.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::missing_safety_doc)]

/// Raw FFI bindings generated by bindgen from llama.h
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

mod engine;
pub mod mask_builder;
pub mod profiler;
pub mod signals;

pub use engine::{LlamaEngine, EngineConfig, set_verbose};
pub use profiler::{HeadProfiler, HeadProfile, HeadSnapshot, ProfilerHandle, profiler_eval_callback, N_BANKS};
pub use signals::{StepSignals, GenerationSignals, compute_entropy_top_k};
